server {
    listen 80;
    server_name localhost;
    
    # HTTP 접속 시 HTTPS로 강제 리다이렉트
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name localhost;

    # 발급한 mkcert 인증서 매핑
    ssl_certificate     /etc/nginx/ssl/nexus.pem;
    ssl_certificate_key /etc/nginx/ssl/nexus-key.pem;

    # 대용량 아티팩트/Docker 이미지 전송 타임아웃 및 버퍼링 최적화
    proxy_send_timeout 120;
    proxy_read_timeout 300;
    proxy_buffering off;
    proxy_request_buffering off;

    location / {
        proxy_pass http://nexus-pg:8081/;
        proxy_pass_header Server;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        
        # Nexus 대용량 파일 업로드 제한 해제 (0 = 무제한)
        client_max_body_size 0;
    }
}
